version: '3.3'
services:
  master:
    image: crawlabteam/crawlab
    container_name: crawlab_master
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_MONGO_HOST: "mongo"
    expose:
      - "${FRONTEND_PORT}"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.2
